//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCSLA.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoCSLAContainer : DbContext
    {
        public DemoCSLAContainer()
            : base("name=DemoCSLAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> ClienteSet { get; set; }
        public virtual DbSet<Producto> ProductoSet { get; set; }
        public virtual DbSet<FacturaCabecera> FacturaCabeceraSet { get; set; }
        public virtual DbSet<FacturaDetalle> FacturaDetalleSet { get; set; }
    }
}
