//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCSLA.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int ID { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual FacturaCabecera Factura { get; set; }
    }
}
