//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCSLA.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCabecera
    {
        public FacturaCabecera()
        {
            this.Detalles = new HashSet<FacturaDetalle>();
        }
    
        public int ID { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<FacturaDetalle> Detalles { get; set; }
    }
}
